[build-system]
requires = [
    "setuptools",
    "Cython",
    "numpy",
]
build-backend = "setuptools.build_meta"

[project]
name = "radex"
version = "0.0.0"
dependencies = [
    "cloudpickle",
    "numpy",
]

[dependency-groups]
test = ["pytest"]
dev = [{include-group = "test"}]


[tool.pytest]
addopts = [
    "--report-chars=a",
]
strict_config = true
strict_markers = true
markers = [
    "slow: Test may be slow to run",
    "compiled: Test has a component comiled at run time"
]
